# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - windows
  - linux
  - osx

julia:
  - 1.2

notifications:
  email: false

env:
  - CODECOV_TOKEN="a77d233c-e261-4406-ae2c-5d11a12a0731"

script:
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder());'
  - bash <(curl -s https://codecov.io/bash)